Add the pages.snippet.getSnippetList event
rainlab/pages-plugin pull request #454
Opened 2020-10-01 14:19 UTC by tomaszstrojny

Hello,

I wanted to remove a snippet from the list of the snippets and haven't found any way. I've decided to add the event because we could use it to add, remove, or edit the snippets. Makes much sense to me.

If the name or the docs are not sufficient, let me know.

Best regards,

Tomasz Strojny

2020-10-01 23:56 UTC, bennothommo commented
@tomaszstrojny I feel that allowing access to the entire snippets property might be fraught with peril. It might be better to add some form of "removeSnippet" method and allow access to the snippet manager through the event instead, like how we do with the navigation events and the like.

What are your thoughts on that?

Also, any event that you want to add must have an event docblock like the following, which details the event and provides an example of its usage: https://github.com/rainlab/pages-plugin/blob/master/classes/Menu.php#L263-L295

2020-10-05 13:54 UTC, tomaszstrojny commented
@bennothommo you're right. It may not be the best idea to allow access to the entire property. Although, this may be used to delete the entry as well as dynamically add or modify the snippet. Let's say I'm using a plugin that has hardcoded snippet name and description and I want to translate them without changing the third-party plugin?

In this case, if we add the `removeSnippet` we should also add something like `addSnippet` or give any other way to dynamically manage them.

I treat `Pages` plugin as a place for the client and as a developer I have to have a possibility to manage every piece of the functionality the client is getting. That's why, in my opinion, we don't have to touch the registered components, as they are accessible only for the developers (CMS section), but snippets are used in the "client space" which has to be fully customizable.

I haven't written the doc block as I was aware that this may not be the best idea. Once we come up with the solution I'll be happy to add it :)

What do you think about it?

2020-10-07 06:55 UTC, bennothommo commented
@tomaszstrojny Yeah I think I'd prefer having specific `addSnippet` and `removeSnippet` methods to control the management of snippets through an event. Would you be willing to adjust your PR to do that for us? :)

2020-10-07 10:07 UTC, tomaszstrojny commented
@bennothommo of course I will do that. Just let me know how would you prefer to have it done.

I would add the methods to the `SnippetManager` as public ones and make `$this` as a parameter of the event. But what event and when to fire them to make it work? I think that the place I've suggested is the most appropriate but let me know if you have any other ideas. The same applies to the name of the event. I'm not sure it will still make sense.

2020-10-12 02:51 UTC, bennothommo commented
@tomaszstrojny here's my thoughts:

- Yep, I would simply make the event parameter the `SnippetManager` instance (ie. `$this`) as you've indicated.
- Add the two new methods to `SnippetManager` - `addSnippet` and `removeSnippet` - that will be available to the event *after* it has already loaded the theme and component snippets. (Pretty much where you have the event already).
- The line `$this->snippets = $snippets;` can be removed as the methods above will cover that already.
- I'd call the event `pages.snippets.listSnippets` to keep with the conventions of other events in the Pages plugin.

Feel free to let me know if you have any other questions.

2020-10-12 12:49 UTC, tomaszstrojny commented
@bennothommo everything's clear. Take a look at the current version and send me your thoughts.

2020-10-12 12:52 UTC, mjauvin commented
@tomaszstrojny some places in the code / comments still reference "snipet" singular...

2020-10-12 12:54 UTC, tomaszstrojny commented
Whoops, all of them probably. Good spot. Give me a moment :)

2020-10-12 13:27 UTC, bennothommo requested changes

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +         * @event pages.snippet.listSnippets
@tomaszstrojny snippets needs to be plural.
```suggestion
         * @event pages.snippets.listSnippets
```

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +         * Gives the ability to manage snippet list dynamically.
```suggestion
         * Gives the ability to manage the snippet list dynamically.
```

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +         * Event::listen('pages.snippet.listSnippets', function(&$manager) {
@tomaszstrojny `$manager` does not need the pass-by-reference (`&`) character, as it is a class instance and is already passed by reference.
```suggestion
         * Event::listen('pages.snippets.listSnippets', function ($manager) {
```

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +         * Event::listen('pages.snippet.listSnippets', function(&$manager) {
```suggestion
         * Event::listen('pages.snippets.listSnippets', function ($manager) {
```

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +        Event::fire('pages.snippet.listSnippets', [&$this]);
```suggestion
        Event::fire('pages.snippets.listSnippets', [$this]);
```

2020-10-12 13:27 UTC, bennothommo commented on classes/SnippetManager.php
> +        $this->snippets = $newSnippets;
@tomaszstrojny This method can be simplified to the following:

```php
$this->snippets = array_filter($this->snippets, function ($snippet) use ($snippetCode) {
    return $snippet->code !== $snippetCode;
});
```

2020-10-12 13:27 UTC, bennothommo commented on docs/documentation.md
> +    Event::listen('pages.snippet.listSnippets', function(&$manager) {
```suggestion
    Event::listen('pages.snippets.listSnippets', function ($manager) {
```

2020-10-12 13:27 UTC, bennothommo commented on docs/documentation.md
> +    Event::listen('pages.snippet.listSnippets', function(&$manager) {
```suggestion
    Event::listen('pages.snippets.listSnippets', function ($manager) {
```

2020-10-12 13:29 UTC, bennothommo commented
@tomaszstrojny I realised that you fixed up the plurals, but you'll need to remove the pass-by-reference calls as well.

2021-03-17 04:57 UTC, merged

2021-03-17 04:57 UTC, daftspunk commented
Thanks @tomaszstrojny !